AllCops:
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - "bin/bundle"

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "config/environments/production.rb"

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - "Gemfile"

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/channels/application_cable/connection_test.rb"
    - "test/test_helper.rb"

Style/Documentation:
  Enabled: false
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "app/helpers/application_helper.rb"
    - "app/mailers/application_mailer.rb"
    - "app/models/application_record.rb"
    - "config/application.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - "config/environments/production.rb"

Style/IfUnlessModifier:
  Exclude:
    - "bin/bundle"

Style/PerlBackrefs:
  Exclude:
    - "bin/bundle"

Style/RedundantFetchBlock:
  Exclude:
    - "config/puma.rb"

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Layout/LineLength:
  Max: 198
