default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>_development

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
