name: Run RSpec Tests

on:
  pull_request:
    branches:
      - main

env:
  RAILS_ENV: test
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_HOST: db
  MYSQL_PORT: 3306
  MYSQL_DATABASE: ordering_service_test
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ordering_service_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_HOST: db
          MYSQL_PORT: 3306
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      mongodb:
        image: mongo:3.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.1"

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h db --silent; do
            echo "Waiting for MySQL to start..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create test database
        run: |
          RAILS_ENV=test bundle exec rails db:create

      - name: Load schema
        run: |
          RAILS_ENV=test bundle exec rails db:schema:load

      - name: Run RSpec
        run: bundle exec rspec
